config/routes.rb
Rails.application.routes.draw do
  resources :guests
  resources :guests

   root 'guests#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	
	belongs_to :guest, :foreign_key => "partner_id"

	def full_name
  		"#{first_name} #{last_name}".strip
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all.order( 'last_name ASC' )
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest_ref = Guest.find(params[:id])
    if @guest_ref.partner_id != nil 
      @spouse_id = @guest_ref.partner_id
      @spouse = Guest.find(@spouse_id)
    end
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:first_name, :last_name, :phone, :email, :birthday, :notes, :partner_id, :anniversary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday, start_year: 1920, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.collection_select(:partner_id, Guest.all, :id, :full_name, include_blank: true) %>
    <%= f.label :partner_id %><br>
    <%#= f.number_field :partner_id %>
  </div>
  <div class="field">
    <%= f.label :anniversary %><br>
    <%= f.date_select :anniversary, start_year: 1950, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/_spouse.html.erb
<div>
<p>
  <strong>Spouse:</strong>
  
  <%= @spouse.first_name %> <%= @spouse.last_name %>
  <%= @guest.anniversary %>
</p>
</div>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      
      <th>Phone</th>
      <th>Email</th>
    <!--   <th>Birthday</th>
      <th>Notes</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.first_name%> <%=guest.last_name %></td>
        <td><%= guest.phone %></td>
        <td><%= guest.email %></td>
      <!--   <td><%#= guest.birthday %></td>
        <td><%#= guest.notes %></td> -->
        <td><%= link_to 'View', guest %></td>
        <td><%#= link_to 'Edit', edit_guest_path(guest) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="link"><%= link_to 'New Guest', new_guest_path %><p>

app/views/guests/new.html.erb
<h2>New Guest</h2>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @guest.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @guest.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @guest.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guest.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @guest.birthday %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @guest.notes %>
</p>

  <% if @spouse != nil %>
  <%= render partial: 'spouse' %>
  <% end %>


<%= link_to 'Edit', edit_guest_path(@guest) %> |
<td><%= link_to 'Destroy', @guest, method: :delete, data: { confirm: 'Are you sure?' } %></td> |
<%= link_to 'Back', guests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GuestList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to "Veranda E Guest Book", guests_path %></h1>
<%= yield %>

</body>
</html>